spring:
  application:
    name: digital-department-ais

  datasource:
    url: jdbc:postgresql://ep-raspy-hill-aqiset9c-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_KI1zLOB8rSNF
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: business
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null

  mail:
    host: smtp.mail.ru
    port: 465
    username: digitaldep.iitu@mail.ru
    password: FscPZZHtk5PzuTOyzeX2
    protocol: smtps
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

camunda.bpm:
  process-engine-name: digital-department-engine
  job-execution:
    enabled: true
    deployment-aware: true

  webapp:
    index-redirect-enabled: true
    header-brand: "Digital Department AIS"

  admin-user:
    id: admin
    password: admin
    first-name: Admin
    last-name: DigitalDep
    email: admin@digital-dep.edu

  database:
    schema-update: true
    type: postgres