spring:
  application:
    name: digital-department-ais

  datasource:
    url: jdbc:postgresql://localhost:5432/digital_department_db
    username: springuser
    password: springpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:

      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
